language: generic
sudo: required

services:
 - docker

before_install:
 - docker build -t icemanftg/docker_react -f Dockerfile.dev .

script:
  - docker run -e CI=true icemanftg/docker_react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "icemanftg_udemy_legacy"
    env: "icemanftgudemylegacy-env"
    bucket_name: "elasticbeanstalk-us-west-2-329849802075"
    bucket_path: "icemanftg_udemy_legacy"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY